services:
  - type: web
    name: smartlibrary-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
    healthCheckPath: /actuator/health
